version: '3.8'

services:

  atena-database:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootroot
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  atena-api:
    build: ./
    container_name: atena-api
    volumes:
      - ./:var/app
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - atena-database
    links:
      - atena-database

volumes:
  postgres: