version: '3.8'

services:

  atena-database:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootroot
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
  
  atena-api:
    container_name: atena-api
    build: ./
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - atena-database
    links:
      - atena-database
    ports:
      - 8080:8080
    env_file:
      - ./.env
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge